#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordingScheduler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="telurint_sqlserver")]
	public partial class TelurIntanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDailyRecording(DailyRecording instance);
    partial void UpdateDailyRecording(DailyRecording instance);
    partial void DeleteDailyRecording(DailyRecording instance);
    partial void InsertAuditLog(AuditLog instance);
    partial void UpdateAuditLog(AuditLog instance);
    partial void DeleteAuditLog(AuditLog instance);
    #endregion
		
		public TelurIntanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelurIntanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelurIntanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelurIntanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DailyRecording> DailyRecordings
		{
			get
			{
				return this.GetTable<DailyRecording>();
			}
		}
		
		public System.Data.Linq.Table<AuditLog> AuditLogs
		{
			get
			{
				return this.GetTable<AuditLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="telurint_sqluser.DailyRecording")]
	public partial class DailyRecording : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CageNumber;
		
		private string _StrainName;
		
		private System.DateTime _RecordDate;
		
		private decimal _HenAgeWeeks;
		
		private System.Nullable<decimal> _HenAgeDays;
		
		private System.Nullable<int> _PopulationStart;
		
		private System.Nullable<int> _DeadHenCount;
		
		private System.Nullable<int> _UnproductiveHenCount;
		
		private System.Nullable<int> _SickHenCount;
		
		private System.Nullable<int> _MoveOutHenCount;
		
		private System.Nullable<int> _MoveInHenCount;
		
		private System.Nullable<int> _PopulationEnd;
		
		private string _ConcentrateType;
		
		private System.Nullable<decimal> _ActualFoodNeededKG;
		
		private System.Nullable<decimal> _SaldoFoodKG;
		
		private System.Nullable<decimal> _FoodNeededTodayKg;
		
		private System.Nullable<decimal> _RemainingFoodKg;
		
		private System.Nullable<decimal> _FoodIntakePerHen;
		
		private System.Nullable<decimal> _FoodIntakeDeviation;
		
		private System.Nullable<int> _PerfectEggCount;
		
		private System.Nullable<decimal> _PerfectEggKg;
		
		private System.Nullable<int> _BrokenEggCount;
		
		private System.Nullable<decimal> _BrokenEggKg;
		
		private System.Nullable<int> _TotalEggCount;
		
		private System.Nullable<decimal> _TotalEggKg;
		
		private System.Nullable<decimal> _ActualHenDay;
		
		private System.Nullable<decimal> _StandardHenDay;
		
		private System.Nullable<decimal> _DailyHenDayDifference;
		
		private System.Nullable<decimal> _ActualEggMassKg;
		
		private System.Nullable<decimal> _StandardEggMassKg;
		
		private System.Nullable<decimal> _EggMassDeviation;
		
		private System.Nullable<decimal> _ActualEggWeightG;
		
		private System.Nullable<decimal> _StandardEggWeightG;
		
		private System.Nullable<decimal> _EggWeightDeviation;
		
		private System.Nullable<decimal> _FeedConversionRatio;
		
		private int _ModifiedBy;
		
		private System.DateTime _ModifiedDate;
		
		private System.Nullable<int> _TelurPutihButir;
		
		private System.Nullable<decimal> _TelurPutihKG;
		
		private System.Nullable<bool> _PeriodeStart;
		
		private System.Nullable<bool> _PeriodeEnd;
		
		private string _GroupName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCageNumberChanging(string value);
    partial void OnCageNumberChanged();
    partial void OnStrainNameChanging(string value);
    partial void OnStrainNameChanged();
    partial void OnRecordDateChanging(System.DateTime value);
    partial void OnRecordDateChanged();
    partial void OnHenAgeWeeksChanging(decimal value);
    partial void OnHenAgeWeeksChanged();
    partial void OnHenAgeDaysChanging(System.Nullable<decimal> value);
    partial void OnHenAgeDaysChanged();
    partial void OnPopulationStartChanging(System.Nullable<int> value);
    partial void OnPopulationStartChanged();
    partial void OnDeadHenCountChanging(System.Nullable<int> value);
    partial void OnDeadHenCountChanged();
    partial void OnUnproductiveHenCountChanging(System.Nullable<int> value);
    partial void OnUnproductiveHenCountChanged();
    partial void OnSickHenCountChanging(System.Nullable<int> value);
    partial void OnSickHenCountChanged();
    partial void OnMoveOutHenCountChanging(System.Nullable<int> value);
    partial void OnMoveOutHenCountChanged();
    partial void OnMoveInHenCountChanging(System.Nullable<int> value);
    partial void OnMoveInHenCountChanged();
    partial void OnPopulationEndChanging(System.Nullable<int> value);
    partial void OnPopulationEndChanged();
    partial void OnConcentrateTypeChanging(string value);
    partial void OnConcentrateTypeChanged();
    partial void OnActualFoodNeededKGChanging(System.Nullable<decimal> value);
    partial void OnActualFoodNeededKGChanged();
    partial void OnSaldoFoodKGChanging(System.Nullable<decimal> value);
    partial void OnSaldoFoodKGChanged();
    partial void OnFoodNeededTodayKgChanging(System.Nullable<decimal> value);
    partial void OnFoodNeededTodayKgChanged();
    partial void OnRemainingFoodKgChanging(System.Nullable<decimal> value);
    partial void OnRemainingFoodKgChanged();
    partial void OnFoodIntakePerHenChanging(System.Nullable<decimal> value);
    partial void OnFoodIntakePerHenChanged();
    partial void OnFoodIntakeDeviationChanging(System.Nullable<decimal> value);
    partial void OnFoodIntakeDeviationChanged();
    partial void OnPerfectEggCountChanging(System.Nullable<int> value);
    partial void OnPerfectEggCountChanged();
    partial void OnPerfectEggKgChanging(System.Nullable<decimal> value);
    partial void OnPerfectEggKgChanged();
    partial void OnBrokenEggCountChanging(System.Nullable<int> value);
    partial void OnBrokenEggCountChanged();
    partial void OnBrokenEggKgChanging(System.Nullable<decimal> value);
    partial void OnBrokenEggKgChanged();
    partial void OnTotalEggCountChanging(System.Nullable<int> value);
    partial void OnTotalEggCountChanged();
    partial void OnTotalEggKgChanging(System.Nullable<decimal> value);
    partial void OnTotalEggKgChanged();
    partial void OnActualHenDayChanging(System.Nullable<decimal> value);
    partial void OnActualHenDayChanged();
    partial void OnStandardHenDayChanging(System.Nullable<decimal> value);
    partial void OnStandardHenDayChanged();
    partial void OnDailyHenDayDifferenceChanging(System.Nullable<decimal> value);
    partial void OnDailyHenDayDifferenceChanged();
    partial void OnActualEggMassKgChanging(System.Nullable<decimal> value);
    partial void OnActualEggMassKgChanged();
    partial void OnStandardEggMassKgChanging(System.Nullable<decimal> value);
    partial void OnStandardEggMassKgChanged();
    partial void OnEggMassDeviationChanging(System.Nullable<decimal> value);
    partial void OnEggMassDeviationChanged();
    partial void OnActualEggWeightGChanging(System.Nullable<decimal> value);
    partial void OnActualEggWeightGChanged();
    partial void OnStandardEggWeightGChanging(System.Nullable<decimal> value);
    partial void OnStandardEggWeightGChanged();
    partial void OnEggWeightDeviationChanging(System.Nullable<decimal> value);
    partial void OnEggWeightDeviationChanged();
    partial void OnFeedConversionRatioChanging(System.Nullable<decimal> value);
    partial void OnFeedConversionRatioChanged();
    partial void OnModifiedByChanging(int value);
    partial void OnModifiedByChanged();
    partial void OnModifiedDateChanging(System.DateTime value);
    partial void OnModifiedDateChanged();
    partial void OnTelurPutihButirChanging(System.Nullable<int> value);
    partial void OnTelurPutihButirChanged();
    partial void OnTelurPutihKGChanging(System.Nullable<decimal> value);
    partial void OnTelurPutihKGChanged();
    partial void OnPeriodeStartChanging(System.Nullable<bool> value);
    partial void OnPeriodeStartChanged();
    partial void OnPeriodeEndChanging(System.Nullable<bool> value);
    partial void OnPeriodeEndChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    #endregion
		
		public DailyRecording()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CageNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CageNumber
		{
			get
			{
				return this._CageNumber;
			}
			set
			{
				if ((this._CageNumber != value))
				{
					this.OnCageNumberChanging(value);
					this.SendPropertyChanging();
					this._CageNumber = value;
					this.SendPropertyChanged("CageNumber");
					this.OnCageNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrainName", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StrainName
		{
			get
			{
				return this._StrainName;
			}
			set
			{
				if ((this._StrainName != value))
				{
					this.OnStrainNameChanging(value);
					this.SendPropertyChanging();
					this._StrainName = value;
					this.SendPropertyChanged("StrainName");
					this.OnStrainNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordDate", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime RecordDate
		{
			get
			{
				return this._RecordDate;
			}
			set
			{
				if ((this._RecordDate != value))
				{
					this.OnRecordDateChanging(value);
					this.SendPropertyChanging();
					this._RecordDate = value;
					this.SendPropertyChanged("RecordDate");
					this.OnRecordDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HenAgeWeeks", DbType="Decimal(5,2) NOT NULL")]
		public decimal HenAgeWeeks
		{
			get
			{
				return this._HenAgeWeeks;
			}
			set
			{
				if ((this._HenAgeWeeks != value))
				{
					this.OnHenAgeWeeksChanging(value);
					this.SendPropertyChanging();
					this._HenAgeWeeks = value;
					this.SendPropertyChanged("HenAgeWeeks");
					this.OnHenAgeWeeksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HenAgeDays", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> HenAgeDays
		{
			get
			{
				return this._HenAgeDays;
			}
			set
			{
				if ((this._HenAgeDays != value))
				{
					this.OnHenAgeDaysChanging(value);
					this.SendPropertyChanging();
					this._HenAgeDays = value;
					this.SendPropertyChanged("HenAgeDays");
					this.OnHenAgeDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PopulationStart", DbType="Int")]
		public System.Nullable<int> PopulationStart
		{
			get
			{
				return this._PopulationStart;
			}
			set
			{
				if ((this._PopulationStart != value))
				{
					this.OnPopulationStartChanging(value);
					this.SendPropertyChanging();
					this._PopulationStart = value;
					this.SendPropertyChanged("PopulationStart");
					this.OnPopulationStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeadHenCount", DbType="Int")]
		public System.Nullable<int> DeadHenCount
		{
			get
			{
				return this._DeadHenCount;
			}
			set
			{
				if ((this._DeadHenCount != value))
				{
					this.OnDeadHenCountChanging(value);
					this.SendPropertyChanging();
					this._DeadHenCount = value;
					this.SendPropertyChanged("DeadHenCount");
					this.OnDeadHenCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnproductiveHenCount", DbType="Int")]
		public System.Nullable<int> UnproductiveHenCount
		{
			get
			{
				return this._UnproductiveHenCount;
			}
			set
			{
				if ((this._UnproductiveHenCount != value))
				{
					this.OnUnproductiveHenCountChanging(value);
					this.SendPropertyChanging();
					this._UnproductiveHenCount = value;
					this.SendPropertyChanged("UnproductiveHenCount");
					this.OnUnproductiveHenCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SickHenCount", DbType="Int")]
		public System.Nullable<int> SickHenCount
		{
			get
			{
				return this._SickHenCount;
			}
			set
			{
				if ((this._SickHenCount != value))
				{
					this.OnSickHenCountChanging(value);
					this.SendPropertyChanging();
					this._SickHenCount = value;
					this.SendPropertyChanged("SickHenCount");
					this.OnSickHenCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveOutHenCount", DbType="Int")]
		public System.Nullable<int> MoveOutHenCount
		{
			get
			{
				return this._MoveOutHenCount;
			}
			set
			{
				if ((this._MoveOutHenCount != value))
				{
					this.OnMoveOutHenCountChanging(value);
					this.SendPropertyChanging();
					this._MoveOutHenCount = value;
					this.SendPropertyChanged("MoveOutHenCount");
					this.OnMoveOutHenCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoveInHenCount", DbType="Int")]
		public System.Nullable<int> MoveInHenCount
		{
			get
			{
				return this._MoveInHenCount;
			}
			set
			{
				if ((this._MoveInHenCount != value))
				{
					this.OnMoveInHenCountChanging(value);
					this.SendPropertyChanging();
					this._MoveInHenCount = value;
					this.SendPropertyChanged("MoveInHenCount");
					this.OnMoveInHenCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PopulationEnd", DbType="Int")]
		public System.Nullable<int> PopulationEnd
		{
			get
			{
				return this._PopulationEnd;
			}
			set
			{
				if ((this._PopulationEnd != value))
				{
					this.OnPopulationEndChanging(value);
					this.SendPropertyChanging();
					this._PopulationEnd = value;
					this.SendPropertyChanged("PopulationEnd");
					this.OnPopulationEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConcentrateType", DbType="NVarChar(50)")]
		public string ConcentrateType
		{
			get
			{
				return this._ConcentrateType;
			}
			set
			{
				if ((this._ConcentrateType != value))
				{
					this.OnConcentrateTypeChanging(value);
					this.SendPropertyChanging();
					this._ConcentrateType = value;
					this.SendPropertyChanged("ConcentrateType");
					this.OnConcentrateTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualFoodNeededKG", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ActualFoodNeededKG
		{
			get
			{
				return this._ActualFoodNeededKG;
			}
			set
			{
				if ((this._ActualFoodNeededKG != value))
				{
					this.OnActualFoodNeededKGChanging(value);
					this.SendPropertyChanging();
					this._ActualFoodNeededKG = value;
					this.SendPropertyChanged("ActualFoodNeededKG");
					this.OnActualFoodNeededKGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoFoodKG", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SaldoFoodKG
		{
			get
			{
				return this._SaldoFoodKG;
			}
			set
			{
				if ((this._SaldoFoodKG != value))
				{
					this.OnSaldoFoodKGChanging(value);
					this.SendPropertyChanging();
					this._SaldoFoodKG = value;
					this.SendPropertyChanged("SaldoFoodKG");
					this.OnSaldoFoodKGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodNeededTodayKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> FoodNeededTodayKg
		{
			get
			{
				return this._FoodNeededTodayKg;
			}
			set
			{
				if ((this._FoodNeededTodayKg != value))
				{
					this.OnFoodNeededTodayKgChanging(value);
					this.SendPropertyChanging();
					this._FoodNeededTodayKg = value;
					this.SendPropertyChanged("FoodNeededTodayKg");
					this.OnFoodNeededTodayKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingFoodKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> RemainingFoodKg
		{
			get
			{
				return this._RemainingFoodKg;
			}
			set
			{
				if ((this._RemainingFoodKg != value))
				{
					this.OnRemainingFoodKgChanging(value);
					this.SendPropertyChanging();
					this._RemainingFoodKg = value;
					this.SendPropertyChanged("RemainingFoodKg");
					this.OnRemainingFoodKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodIntakePerHen", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> FoodIntakePerHen
		{
			get
			{
				return this._FoodIntakePerHen;
			}
			set
			{
				if ((this._FoodIntakePerHen != value))
				{
					this.OnFoodIntakePerHenChanging(value);
					this.SendPropertyChanging();
					this._FoodIntakePerHen = value;
					this.SendPropertyChanged("FoodIntakePerHen");
					this.OnFoodIntakePerHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodIntakeDeviation", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FoodIntakeDeviation
		{
			get
			{
				return this._FoodIntakeDeviation;
			}
			set
			{
				if ((this._FoodIntakeDeviation != value))
				{
					this.OnFoodIntakeDeviationChanging(value);
					this.SendPropertyChanging();
					this._FoodIntakeDeviation = value;
					this.SendPropertyChanged("FoodIntakeDeviation");
					this.OnFoodIntakeDeviationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfectEggCount", DbType="Int")]
		public System.Nullable<int> PerfectEggCount
		{
			get
			{
				return this._PerfectEggCount;
			}
			set
			{
				if ((this._PerfectEggCount != value))
				{
					this.OnPerfectEggCountChanging(value);
					this.SendPropertyChanging();
					this._PerfectEggCount = value;
					this.SendPropertyChanged("PerfectEggCount");
					this.OnPerfectEggCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfectEggKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PerfectEggKg
		{
			get
			{
				return this._PerfectEggKg;
			}
			set
			{
				if ((this._PerfectEggKg != value))
				{
					this.OnPerfectEggKgChanging(value);
					this.SendPropertyChanging();
					this._PerfectEggKg = value;
					this.SendPropertyChanged("PerfectEggKg");
					this.OnPerfectEggKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrokenEggCount", DbType="Int")]
		public System.Nullable<int> BrokenEggCount
		{
			get
			{
				return this._BrokenEggCount;
			}
			set
			{
				if ((this._BrokenEggCount != value))
				{
					this.OnBrokenEggCountChanging(value);
					this.SendPropertyChanging();
					this._BrokenEggCount = value;
					this.SendPropertyChanged("BrokenEggCount");
					this.OnBrokenEggCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrokenEggKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> BrokenEggKg
		{
			get
			{
				return this._BrokenEggKg;
			}
			set
			{
				if ((this._BrokenEggKg != value))
				{
					this.OnBrokenEggKgChanging(value);
					this.SendPropertyChanging();
					this._BrokenEggKg = value;
					this.SendPropertyChanged("BrokenEggKg");
					this.OnBrokenEggKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalEggCount", DbType="Int")]
		public System.Nullable<int> TotalEggCount
		{
			get
			{
				return this._TotalEggCount;
			}
			set
			{
				if ((this._TotalEggCount != value))
				{
					this.OnTotalEggCountChanging(value);
					this.SendPropertyChanging();
					this._TotalEggCount = value;
					this.SendPropertyChanged("TotalEggCount");
					this.OnTotalEggCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalEggKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TotalEggKg
		{
			get
			{
				return this._TotalEggKg;
			}
			set
			{
				if ((this._TotalEggKg != value))
				{
					this.OnTotalEggKgChanging(value);
					this.SendPropertyChanging();
					this._TotalEggKg = value;
					this.SendPropertyChanged("TotalEggKg");
					this.OnTotalEggKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualHenDay", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ActualHenDay
		{
			get
			{
				return this._ActualHenDay;
			}
			set
			{
				if ((this._ActualHenDay != value))
				{
					this.OnActualHenDayChanging(value);
					this.SendPropertyChanging();
					this._ActualHenDay = value;
					this.SendPropertyChanged("ActualHenDay");
					this.OnActualHenDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardHenDay", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> StandardHenDay
		{
			get
			{
				return this._StandardHenDay;
			}
			set
			{
				if ((this._StandardHenDay != value))
				{
					this.OnStandardHenDayChanging(value);
					this.SendPropertyChanging();
					this._StandardHenDay = value;
					this.SendPropertyChanged("StandardHenDay");
					this.OnStandardHenDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailyHenDayDifference", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DailyHenDayDifference
		{
			get
			{
				return this._DailyHenDayDifference;
			}
			set
			{
				if ((this._DailyHenDayDifference != value))
				{
					this.OnDailyHenDayDifferenceChanging(value);
					this.SendPropertyChanging();
					this._DailyHenDayDifference = value;
					this.SendPropertyChanged("DailyHenDayDifference");
					this.OnDailyHenDayDifferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualEggMassKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ActualEggMassKg
		{
			get
			{
				return this._ActualEggMassKg;
			}
			set
			{
				if ((this._ActualEggMassKg != value))
				{
					this.OnActualEggMassKgChanging(value);
					this.SendPropertyChanging();
					this._ActualEggMassKg = value;
					this.SendPropertyChanged("ActualEggMassKg");
					this.OnActualEggMassKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardEggMassKg", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> StandardEggMassKg
		{
			get
			{
				return this._StandardEggMassKg;
			}
			set
			{
				if ((this._StandardEggMassKg != value))
				{
					this.OnStandardEggMassKgChanging(value);
					this.SendPropertyChanging();
					this._StandardEggMassKg = value;
					this.SendPropertyChanged("StandardEggMassKg");
					this.OnStandardEggMassKgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EggMassDeviation", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> EggMassDeviation
		{
			get
			{
				return this._EggMassDeviation;
			}
			set
			{
				if ((this._EggMassDeviation != value))
				{
					this.OnEggMassDeviationChanging(value);
					this.SendPropertyChanging();
					this._EggMassDeviation = value;
					this.SendPropertyChanged("EggMassDeviation");
					this.OnEggMassDeviationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualEggWeightG", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ActualEggWeightG
		{
			get
			{
				return this._ActualEggWeightG;
			}
			set
			{
				if ((this._ActualEggWeightG != value))
				{
					this.OnActualEggWeightGChanging(value);
					this.SendPropertyChanging();
					this._ActualEggWeightG = value;
					this.SendPropertyChanged("ActualEggWeightG");
					this.OnActualEggWeightGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardEggWeightG", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> StandardEggWeightG
		{
			get
			{
				return this._StandardEggWeightG;
			}
			set
			{
				if ((this._StandardEggWeightG != value))
				{
					this.OnStandardEggWeightGChanging(value);
					this.SendPropertyChanging();
					this._StandardEggWeightG = value;
					this.SendPropertyChanged("StandardEggWeightG");
					this.OnStandardEggWeightGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EggWeightDeviation", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> EggWeightDeviation
		{
			get
			{
				return this._EggWeightDeviation;
			}
			set
			{
				if ((this._EggWeightDeviation != value))
				{
					this.OnEggWeightDeviationChanging(value);
					this.SendPropertyChanging();
					this._EggWeightDeviation = value;
					this.SendPropertyChanged("EggWeightDeviation");
					this.OnEggWeightDeviationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedConversionRatio", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> FeedConversionRatio
		{
			get
			{
				return this._FeedConversionRatio;
			}
			set
			{
				if ((this._FeedConversionRatio != value))
				{
					this.OnFeedConversionRatioChanging(value);
					this.SendPropertyChanging();
					this._FeedConversionRatio = value;
					this.SendPropertyChanged("FeedConversionRatio");
					this.OnFeedConversionRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="Int NOT NULL")]
		public int ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelurPutihButir", DbType="Int")]
		public System.Nullable<int> TelurPutihButir
		{
			get
			{
				return this._TelurPutihButir;
			}
			set
			{
				if ((this._TelurPutihButir != value))
				{
					this.OnTelurPutihButirChanging(value);
					this.SendPropertyChanging();
					this._TelurPutihButir = value;
					this.SendPropertyChanged("TelurPutihButir");
					this.OnTelurPutihButirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelurPutihKG", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TelurPutihKG
		{
			get
			{
				return this._TelurPutihKG;
			}
			set
			{
				if ((this._TelurPutihKG != value))
				{
					this.OnTelurPutihKGChanging(value);
					this.SendPropertyChanging();
					this._TelurPutihKG = value;
					this.SendPropertyChanged("TelurPutihKG");
					this.OnTelurPutihKGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodeStart", DbType="Bit")]
		public System.Nullable<bool> PeriodeStart
		{
			get
			{
				return this._PeriodeStart;
			}
			set
			{
				if ((this._PeriodeStart != value))
				{
					this.OnPeriodeStartChanging(value);
					this.SendPropertyChanging();
					this._PeriodeStart = value;
					this.SendPropertyChanged("PeriodeStart");
					this.OnPeriodeStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodeEnd", DbType="Bit")]
		public System.Nullable<bool> PeriodeEnd
		{
			get
			{
				return this._PeriodeEnd;
			}
			set
			{
				if ((this._PeriodeEnd != value))
				{
					this.OnPeriodeEndChanging(value);
					this.SendPropertyChanging();
					this._PeriodeEnd = value;
					this.SendPropertyChanged("PeriodeEnd");
					this.OnPeriodeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(250)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="telurint_sqluser.AuditLog")]
	public partial class AuditLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _EmployeeName;
		
		private System.DateTime _CreatedDate;
		
		private string _ActionType;
		
		private string _ActionDescription;
		
		private int _EmployeeID;
		
		private string _LogType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnActionTypeChanging(string value);
    partial void OnActionTypeChanged();
    partial void OnActionDescriptionChanging(string value);
    partial void OnActionDescriptionChanged();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnLogTypeChanging(string value);
    partial void OnLogTypeChanged();
    #endregion
		
		public AuditLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this.OnEmployeeNameChanging(value);
					this.SendPropertyChanging();
					this._EmployeeName = value;
					this.SendPropertyChanged("EmployeeName");
					this.OnEmployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ActionType
		{
			get
			{
				return this._ActionType;
			}
			set
			{
				if ((this._ActionType != value))
				{
					this.OnActionTypeChanging(value);
					this.SendPropertyChanging();
					this._ActionType = value;
					this.SendPropertyChanged("ActionType");
					this.OnActionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ActionDescription
		{
			get
			{
				return this._ActionDescription;
			}
			set
			{
				if ((this._ActionDescription != value))
				{
					this.OnActionDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ActionDescription = value;
					this.SendPropertyChanged("ActionDescription");
					this.OnActionDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int NOT NULL")]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LogType
		{
			get
			{
				return this._LogType;
			}
			set
			{
				if ((this._LogType != value))
				{
					this.OnLogTypeChanging(value);
					this.SendPropertyChanging();
					this._LogType = value;
					this.SendPropertyChanged("LogType");
					this.OnLogTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
